### ISSUE TITLE
Error with PortalAuth Cannot find info anywhere

### ISSUE THREAD

**Issue by Drumshtick** [hak5/wifipineapple-modules#92]
I populate all fields with default and switch the target to starbucks.com and get this error. I have tried multiple different targets and it always spits out the same.

Error is called:   clone_error_01_59_55.txt
Text:
Traceback (most recent call last): File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 4, in from PortalCloner import PortalCloner File "/pineapple/modules/PortalAuth/includes/scripts/PortalCloner.py", line 12, in import requests File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/__init__.py", line 53, in from .packages.urllib3.contrib import pyopenssl File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/__init__.py", line 63, in load_module __import__(name) File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/__init__.py", line 10, in from .connectionpool import ( File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/connectionpool.py", line 37, in from .request import RequestMethods File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/request.py", line 6, in from .filepost import encode_multipart_formdata File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/filepost.py", line 10, in writer = codecs.lookup('utf-8')[3] LookupError: unknown encoding: utf-8

**Comment by okoester** [comment]
Did you receive any information on this? Same problem here after upgrading to the actual pineapple (tetra) firmware...
